#!/usr/bin/env python3
# Generate MincEmbeddedMeta.cpp: the AEGP's TEXT metadata — presets.json, extension-defaults.json,
# and the preset config-*.ocio (YAML text, NO LUTs) — baked into the AEGP binary so the panel's
# dropdowns, looks and interpret work with ZERO config store on disk ("the plugin is the package"
# on the authoring side too). Lookup by basename. Stored RAW (uncompressed byte arrays) so the mac
# AEGP needs no zlib link; the text is small (~0.9 MB) and the effect already carries the LUTs.
#   usage: gen_embedded_meta.py <out.cpp> <config-root dir>   (dist = <config-root>/dist)
import sys, os

def die(m): sys.stderr.write("gen_embedded_meta: " + m + "\n"); sys.exit(1)

if len(sys.argv) != 3: die("usage: <out.cpp> <config-root-dir>")
out_path, root = sys.argv[1], sys.argv[2]
dist = os.path.join(root, "dist")

files = {}
def add(path):
    if not os.path.exists(path): die("not found: " + path)
    b = os.path.basename(path)
    if b in files: die("duplicate basename: " + b)
    files[b] = open(path, "rb").read()

add(os.path.join(dist, "presets.json"))
add(os.path.join(root, "extension-defaults.json"))
add(os.path.join(root, "render-presets.json"))
cfgs = sorted(f for f in os.listdir(dist) if f.startswith("config-") and f.endswith(".ocio"))
if not cfgs: die("no config-*.ocio in " + dist)
for c in cfgs: add(os.path.join(dist, c))

def emit_array(w, sym, data):
    w.write("static const unsigned char %s[] = {" % sym)
    line = []
    for b in data:
        line.append("%d," % b)
        if len(line) >= 32:
            w.write("\n" + "".join(line)); line = []
    if line: w.write("\n" + "".join(line))
    w.write("\n};\n")

entries = []
with open(out_path, "w") as w:
    w.write("/* GENERATED by plugin/cmake/gen_embedded_meta.py — do not edit. */\n")
    w.write('#include "MincEmbeddedMeta.h"\n\nnamespace {\n')
    for i, name in enumerate(sorted(files)):
        emit_array(w, "m%d" % i, files[name])
        entries.append((name, "m%d" % i, len(files[name])))
    w.write("struct E { const char *name; const unsigned char *d; unsigned len; };\n")
    w.write("static const E kMeta[] = {\n")
    for name, sym, ln in entries:
        w.write('  { "%s", %s, %du },\n' % (name.replace('"', '\\"'), sym, ln))
    w.write("};\n")
    w.write("static const int kMeta_n = %d;\n" % len(entries))
    w.write("""} // namespace

std::string MincEmbeddedMetaText(const std::string &b) {
    for (int i = 0; i < kMeta_n; ++i)
        if (b == kMeta[i].name) return std::string((const char *)kMeta[i].d, kMeta[i].len);
    return std::string();
}
bool MincEmbeddedMetaHas(const std::string &b) {
    for (int i = 0; i < kMeta_n; ++i) if (b == kMeta[i].name) return true;
    return false;
}
""")
sys.stderr.write("gen_embedded_meta: %d files embedded (%d bytes) -> %s\n" %
                 (len(entries), sum(len(v) for v in files.values()), out_path))
