#!/usr/bin/env python3
# Generate MincEmbeddedConfigs.cpp: the preset OCIO configs + their LUT trees, zlib-compressed
# and baked into the effect binary so rendering needs no filesystem. Lookup by basename.
#   usage: gen_embedded_configs.py <out.cpp> <config/dist dir>
import sys, os, json, zlib

def die(m): sys.stderr.write("gen_embedded_configs: " + m + "\n"); sys.exit(1)

if len(sys.argv) != 3: die("usage: <out.cpp> <config-dist-dir>")
out_path, dist = sys.argv[1], sys.argv[2]

# preset configs from presets.json (the ones the effect can be pinned to)
pj = os.path.join(dist, "presets.json")
if not os.path.exists(pj): die("presets.json not found in " + dist)
presets = json.load(open(pj))
pmap = presets.get("presets", presets)
config_names = []
for k, v in (pmap.items() if isinstance(pmap, dict) else [(p.get("key"), p) for p in pmap]):
    c = v.get("config") if isinstance(v, dict) else None
    if c and c not in config_names: config_names.append(c)
if not config_names: die("no preset configs found")

# LUT trees (search_path: icc:luts:filmic) — basenames are unique across them
lut_files = {}
for sub in ("luts", "filmic", "icc"):
    d = os.path.join(dist, sub)
    if not os.path.isdir(d): continue
    for fn in os.listdir(d):
        p = os.path.join(d, fn)
        if not os.path.isfile(p): continue
        if fn.lower().endswith((".md",)): continue
        if fn in lut_files: die("duplicate LUT basename across trees: " + fn)
        lut_files[fn] = p

def emit_array(w, sym, data):
    z = zlib.compress(data, 9)
    w.write("static const unsigned char %s[] = {" % sym)
    # compact hex, wrapped
    line = []
    for i, b in enumerate(z):
        line.append("%d," % b)
        if len(line) >= 32:
            w.write("\n" + "".join(line)); line = []
    if line: w.write("\n" + "".join(line))
    w.write("\n};\n")
    return len(z), len(data)

entries_cfg, entries_lut = [], []
with open(out_path, "w") as w:
    w.write("/* GENERATED by plugin/cmake/gen_embedded_configs.py — do not edit. */\n")
    w.write('#include "MincEmbeddedConfigs.h"\n#include <zlib.h>\n#include <cstring>\n\nnamespace {\n')
    idx = 0
    for name in config_names:
        p = os.path.join(dist, name)
        if not os.path.exists(p): die("config not found: " + p)
        zlen, rawlen = emit_array(w, "c%d" % idx, open(p, "rb").read())
        entries_cfg.append((name, "c%d" % idx, rawlen)); idx += 1
    for name in sorted(lut_files):
        zlen, rawlen = emit_array(w, "l%d" % idx, open(lut_files[name], "rb").read())
        entries_lut.append((name, "l%d" % idx, rawlen)); idx += 1
    w.write("struct E { const char *name; const unsigned char *z; unsigned zlen; unsigned rawlen; };\n")
    def tbl(nm, entries):
        w.write("static const E %s[] = {\n" % nm)
        for name, sym, rawlen in entries:
            w.write('  { "%s", %s, (unsigned)sizeof(%s), %du },\n' % (name.replace('"','\\"'), sym, sym, rawlen))
        w.write("};\n")
        w.write("static const int %s_n = %d;\n" % (nm, len(entries)))
    tbl("kConfigs", entries_cfg)
    tbl("kLuts", entries_lut)
    w.write("""
static bool inflate1(const E &e, std::string &out) {
    out.resize(e.rawlen);
    uLongf dl = e.rawlen;
    if (uncompress((Bytef *)&out[0], &dl, e.z, e.zlen) != Z_OK) { out.clear(); return false; }
    out.resize((size_t)dl);
    return true;
}
static const E *find(const E *t, int n, const std::string &b) {
    for (int i = 0; i < n; ++i) if (b == t[i].name) return &t[i];
    return nullptr;
}
} // namespace

std::string MincEmbeddedConfig(const std::string &b) {
    const E *e = find(kConfigs, kConfigs_n, b);
    std::string s; if (e) inflate1(*e, s); return s;
}
std::vector<uint8_t> MincEmbeddedLut(const std::string &b) {
    const E *e = find(kLuts, kLuts_n, b);
    std::string s; if (e && inflate1(*e, s)) return std::vector<uint8_t>(s.begin(), s.end());
    return std::vector<uint8_t>();
}
bool MincEmbeddedHasConfig(const std::string &b) { return find(kConfigs, kConfigs_n, b) != nullptr; }
""")
sys.stderr.write("gen_embedded_configs: %d configs + %d LUTs embedded -> %s\n" %
                 (len(entries_cfg), len(entries_lut), out_path))
